"""
bias_blp_cross_emit.py — emit bias_blp_cross_viz.pine with the ENGINE's blp14 crosses as plotshapes
(Joe 0621). The 3 lines come from request.security("1") (1-min ×7 blown-up, == the engine's basis) so
the python crosses sit on the actual line crossings; the crosses themselves are computed HERE and
shipped as timestamp arrays → plotshape (no Pine cross-detection). Run the .pine on a 30s pane.
Range default = the TV-export 2 weeks; narrow R0/R1 if TV chokes on the array size.
"""
import sys; sys.path.insert(0, '/home/joe/thecodes')
import datetime as dtm
from datetime import timezone
import numpy as np
from optimus9.config import get_db_config
from optimus9 import DatabaseManager
from optimus9.compute.indicator_computer import IndicatorComputer as IC
import bias_machine as bm

R0 = int(dtm.datetime(2026, 6, 6, tzinfo=timezone.utc).timestamp() * 1000)
R1 = int(dtm.datetime(2026, 6, 21, tzinfo=timezone.utc).timestamp() * 1000)
X = 7                                                          # TF7→TF1 blow-up

db = DatabaseManager(**get_db_config()); db.connect()
latest = int(db.execute('SELECT MAX(kc_timestamp) m FROM kline_collection', fetch=True)[0]['m'])
W = bm.BiasWindow(db, latest, lookback=336, warmup=160, cfg=bm.BiasConfig(osc='s12m', trigger_tf=12, gate='oob'))
db.disconnect()
f1 = IC.resample(W.base, 60); t1 = f1['timestamp'].to_numpy()
L = {'m': IC.f_bb(IC.build_source(f1, 'hlc3'), 20 * X, 0.77),
     'M': IC.f_bb(IC.build_source(f1, 'ohlc4'), 74 * X, 0.73),
     'r': IC.f_k(IC.build_source(f1, 'hl2'), 12 * X, 12 * X, 10 * X)}

TYPES = ['mM_over', 'mM_under', 'mr_over', 'mr_under', 'Mr_over', 'Mr_under']
cx = {k: [] for k in TYPES}
for a, b in (('m', 'M'), ('m', 'r'), ('M', 'r')):
    A, B = L[a], L[b]
    for i in range(1, len(A)):
        if any(np.isnan(v) for v in (A[i], B[i], A[i - 1], B[i - 1])):
            continue
        t = int(t1[i])
        if not (R0 <= t < R1):
            continue
        if A[i] > B[i] and A[i - 1] <= B[i - 1]:
            cx[f'{a}{b}_over'].append(t)
        elif A[i] < B[i] and A[i - 1] >= B[i - 1]:
            cx[f'{a}{b}_under'].append(t)

print('engine crosses in range:', {k: len(v) for k, v in cx.items()}, '· total', sum(len(v) for v in cx.values()))
arr = lambda v: 'array.from(' + ', '.join(str(x) for x in v) + ')' if v else 'array.new<int>()'
# shape per direction, colour per pair (white mM · aqua mr · orange Mr)
STYLE = {'mM_over': ('shape.triangleup', 'location.bottom', 'color.white'),
         'mM_under': ('shape.triangledown', 'location.top', 'color.white'),
         'mr_over': ('shape.triangleup', 'location.bottom', 'color.aqua'),
         'mr_under': ('shape.triangledown', 'location.top', 'color.aqua'),
         'Mr_over': ('shape.triangleup', 'location.bottom', 'color.orange'),
         'Mr_under': ('shape.triangledown', 'location.top', 'color.orange')}
lines_arr = '\n'.join(f'var int[] CX_{k} = {arr(cx[k])}' for k in TYPES)
shapes = '\n'.join(
    f'plotshape(array.binary_search(CX_{k}, time) >= 0, "{k}", {STYLE[k][0]}, {STYLE[k][1]}, {STYLE[k][2]}, size = size.tiny)'
    for k in TYPES)

body = f'''//@version=5
// bias_blp_cross_viz.pine — GENERATED by bias_blp_cross_emit.py. The 3 blp14 lines (1-min ×{X} blown-up
// via request.security) + the ENGINE's crosses shipped as timestamp arrays → plotshape. Run on a 30s pane.
indicator("blp14 cross viz (engine)", overlay = false)
f_bbpct(src, len, mult) =>
    basis = ta.sma(src, len)
    dev   = mult * ta.stdev(src, len)
    40.0 * (src - (basis - dev)) / (2.0 * dev) + 30.0
f_kline(src, rl, sl, kl) =>
    rs = ta.rsi(src, rl)
    ta.sma(ta.stoch(rs, rs, rs, sl), kl)
m = request.security(syminfo.tickerid, "1", f_bbpct(hlc3,  {20*X}, 0.77))
M = request.security(syminfo.tickerid, "1", f_bbpct(ohlc4, {74*X}, 0.73))
r = request.security(syminfo.tickerid, "1", f_kline(hl2,   {12*X}, {12*X}, {10*X}))
plot(m, "m", color.aqua, 2)
plot(M, "M", color.orange, 2)
plot(r, "r", color.fuchsia, 2)
hline(85, "OOB hi", color.gray)
hline(15, "OOB lo", color.gray)

// ── engine crosses (from python) ──
{lines_arr}
{shapes}
'''
path = '/home/joe/thecodes/bias_blp_cross_viz.pine'
open(path, 'w').write(body)
print('→', path)
